## Flow Formula
* I just inplement the simple formula of PageRank. This kind of model cannot be used to Large Scale Data, unless you change the DataStructure

In [2]:
import numpy as np
import random

In [23]:
def create_data(N, alpha=0.5): # random > alpha, then here is a edge.
    G = np.zeros((N, N))
    for i in range(N):
        for j in range(N):
            if i == j:
                continue
            if random.random() < alpha:
                G[i][j] = 1
    return G

In [24]:
G = create_data(10)

In [25]:
G

array([[0., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 1., 1., 1., 0.],
       [1., 0., 1., 0., 1., 0., 0., 1., 0., 1.],
       [0., 1., 1., 1., 0., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 1., 0., 1., 0.]])

In [26]:
def GtoM(G, N):
    M = np.zeros((N, N))
    for i in range(N):
        D_i = sum(G[i])
        if D_i == 0:
            continue
        for j in range(N):
            M[j][i] = G[i][j] / D_i # watch out! M_j_i instead of M_i_j
    return M

In [27]:
M = GtoM(G, 10)

In [28]:
M

array([[0.        , 0.25      , 0.        , 0.2       , 0.        ,
        0.14285714, 0.        , 0.        , 0.33333333, 0.        ],
       [0.16666667, 0.        , 0.16666667, 0.        , 0.14285714,
        0.14285714, 0.        , 0.25      , 0.        , 0.        ],
       [0.16666667, 0.        , 0.        , 0.2       , 0.14285714,
        0.14285714, 0.        , 0.        , 0.        , 0.2       ],
       [0.        , 0.        , 0.16666667, 0.        , 0.14285714,
        0.14285714, 0.        , 0.25      , 0.        , 0.2       ],
       [0.        , 0.25      , 0.        , 0.2       , 0.        ,
        0.        , 0.33333333, 0.        , 0.        , 0.2       ],
       [0.        , 0.        , 0.16666667, 0.        , 0.14285714,
        0.        , 0.        , 0.25      , 0.33333333, 0.        ],
       [0.16666667, 0.25      , 0.16666667, 0.        , 0.14285714,
        0.14285714, 0.        , 0.        , 0.        , 0.2       ],
       [0.16666667, 0.        , 0.1666666

In [29]:
def PageRank(M, N, T=300, eps=1e-6):
    R = np.ones(N) / N
    for time in range(T):
        R_new = np.dot(M, R)
        if np.linalg.norm(R_new - R) < eps:
            break
        R = R_new.copy()
    return R_new

In [35]:
values = PageRank(M, 10, T=2000)
values

array([0.09972576, 0.09193927, 0.07843151, 0.09125886, 0.08925602,
       0.10407245, 0.09623654, 0.13851257, 0.13086464, 0.07970237])

In [34]:
sum(values)

0.9999999999999996

In [36]:
def PageRank_(M, N, T=300, eps=1e-6, beta=0.8):
    R = np.ones(N) / N
    teleport = np.ones(N) / N
    for time in range(T):
        R_new = beta * np.dot(M, R) + (1-beta)*teleport
        if np.linalg.norm(R_new - R) < eps:
            break
        R = R_new.copy()
    return R_new

In [37]:
values = PageRank_(M, 10, T=2000)
values

array([0.09815807, 0.09250429, 0.08376235, 0.09300133, 0.09324628,
       0.10108776, 0.09855127, 0.13019363, 0.12458992, 0.0849051 ])