## Google Formula
* I just inplement the simple formula of PageRank. This kind of model cannot be used to Large Scale Data, unless you change the DataStructure

In [2]:
import numpy as np
import random

In [3]:
def create_data(N, alpha=0.5): # random > alpha, then here is a edge.
    G = np.zeros((N, N))
    for i in range(N):
        for j in range(N):
            if i == j:
                continue
            if random.random() < alpha:
                G[i][j] = 1
    return G

In [4]:
G = create_data(10)

In [5]:
G

array([[0., 1., 1., 0., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 1., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 1., 1., 1., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0., 0.],
       [1., 1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 0., 1., 1.],
       [0., 0., 1., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 1., 1., 0., 0., 0., 1., 0.]])

In [6]:
def GtoM(G, N):
    M = np.zeros((N, N))
    for i in range(N):
        D_i = sum(G[i])
        if D_i == 0:
            continue
        for j in range(N):
            M[j][i] = G[i][j] / D_i # watch out! M_j_i instead of M_i_j
    return M

In [7]:
M = GtoM(G, 10)

In [8]:
M

array([[0.        , 0.        , 0.        , 0.25      , 0.        ,
        0.25      , 0.        , 0.        , 0.        , 0.        ],
       [0.2       , 0.        , 0.16666667, 0.        , 0.        ,
        0.25      , 0.33333333, 0.2       , 0.        , 0.25      ],
       [0.2       , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.33333333, 0.        , 0.5       , 0.        ],
       [0.        , 0.33333333, 0.16666667, 0.        , 0.        ,
        0.        , 0.        , 0.2       , 0.        , 0.25      ],
       [0.        , 0.33333333, 0.16666667, 0.25      , 0.        ,
        0.25      , 0.        , 0.        , 0.        , 0.25      ],
       [0.2       , 0.        , 0.16666667, 0.25      , 0.        ,
        0.        , 0.        , 0.2       , 0.5       , 0.        ],
       [0.        , 0.        , 0.16666667, 0.        , 0.5       ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.2       , 0.        , 0.1666666

In [9]:
def PageRank(M, N, T=300, eps=1e-6, beta=0.8):
    R = np.ones(N) / N
    teleport = np.ones(N) / N
    for time in range(T):
        R_new = beta * np.dot(M, R) + (1-beta)*teleport
        if np.linalg.norm(R_new - R) < eps:
            break
        R = R_new.copy()
    return R_new

In [10]:
values = PageRank(M, 10, T=2000)
values

array([0.06423149, 0.1221873 , 0.09415584, 0.09800476, 0.12353606,
       0.12315282, 0.08196852, 0.11687612, 0.10505158, 0.07083551])

In [11]:
sum(values)

1.0